services:
  service:
    image: house-service
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '8080:8080'
    volumes:
      - ./config.env:/root/config.env
      - ./migrations/:/migrations/
  postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: [ "CMD-SHELL","pg_isready -d postgres -U postgres" ]
      interval: 3s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'