services:
  service:
    image: house-service
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    volumes:
      - ./config.env:/root/config.env
      - ./migrations/:/migrations/
  postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'