// Code generated by MockGen. DO NOT EDIT.
// Source: ./house.go
//
// Generated by this command:
//
//	mockgen -source ./house.go -destination=./mocks/house_db.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	pgx "github.com/jackc/pgx/v5"
	pgconn "github.com/jackc/pgx/v5/pgconn"
	gomock "go.uber.org/mock/gomock"
)

// MockDBHouse is a mock of DBHouse interface.
type MockDBHouse struct {
	ctrl     *gomock.Controller
	recorder *MockDBHouseMockRecorder
}

// MockDBHouseMockRecorder is the mock recorder for MockDBHouse.
type MockDBHouseMockRecorder struct {
	mock *MockDBHouse
}

// NewMockDBHouse creates a new mock instance.
func NewMockDBHouse(ctrl *gomock.Controller) *MockDBHouse {
	mock := &MockDBHouse{ctrl: ctrl}
	mock.recorder = &MockDBHouseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBHouse) EXPECT() *MockDBHouseMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockDBHouse) Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockDBHouseMockRecorder) Exec(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockDBHouse)(nil).Exec), varargs...)
}

// QueryRow mocks base method.
func (m *MockDBHouse) QueryRow(ctx context.Context, sql string, args ...any) pgx.Row {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(pgx.Row)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *MockDBHouseMockRecorder) QueryRow(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*MockDBHouse)(nil).QueryRow), varargs...)
}

// MockRowDBHouse is a mock of RowDBHouse interface.
type MockRowDBHouse struct {
	ctrl     *gomock.Controller
	recorder *MockRowDBHouseMockRecorder
}

// MockRowDBHouseMockRecorder is the mock recorder for MockRowDBHouse.
type MockRowDBHouseMockRecorder struct {
	mock *MockRowDBHouse
}

// NewMockRowDBHouse creates a new mock instance.
func NewMockRowDBHouse(ctrl *gomock.Controller) *MockRowDBHouse {
	mock := &MockRowDBHouse{ctrl: ctrl}
	mock.recorder = &MockRowDBHouseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRowDBHouse) EXPECT() *MockRowDBHouseMockRecorder {
	return m.recorder
}

// Scan mocks base method.
func (m *MockRowDBHouse) Scan(dest ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range dest {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Scan", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Scan indicates an expected call of Scan.
func (mr *MockRowDBHouseMockRecorder) Scan(dest ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockRowDBHouse)(nil).Scan), dest...)
}
